speech = "She said: \"Hi\""
print(speech)


days = 365
print(f"There are {days} FUCKING DAYS  in a year")


# while 5 > 1:
#             print("I'm a survivor")



Fruits= ["Apple","Orange","Banana"]

for i in Fruits:
    print(f"I will eat {i}")              #f string 
    
    
scores = [34, 67, 99, 105]
for s in scores:
     if s > 100:
         print("Invalid")
         break
print(s)


all_fruits = ["apple", "banana", "orange"]

all_fruits.append("pear")
print(all_fruits)


letters = ["a","b","c","d"]
letters[1:2]


